architecture: AASIST
pretrained_weights_path: ./backbones/pretrained_weights/AASIST_ST_RB_2.8145.pth
nb_samp: 64600
first_conv: 128
filts: [70, [1, 32], [32, 32], [32, 64], [64, 64]]
gat_dims: [64, 32]
pool_ratios: [0.5, 0.7, 0.5, 0.5]
temperatures: [2.0, 2.0, 100.0, 100.0]